### ISSUE TITLE
Array.Copy Exception when running against System.Formats.Cbor

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/api-docs-sync#159]
cc @smasher164 

Using the latest bits in main. Used this command:
```
PortToTripleSlash.exe -CsProj D:\runtime\src\libraries\System.Formats.Cbor\src\System.Formats.Cbor.csproj -Docs D:\dotnet-api-docs\xml -IncludedAssemblies System.Formats.Cbor
```

Callstack:
```
 ---> System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at ApiDocsSync.PortToTripleSlash.AllTypesVisitor.VisitNamedType(INamedTypeSymbol symbol) in D:\api-docs-sync\src\PortToTripleSlash\src\libraries\AllTypesVisitor.cs:line 21
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamedTypeSymbol.Accept(SymbolVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept(SymbolVisitor visitor)
   at ApiDocsSync.PortToTripleSlash.AllTypesVisitor.<VisitNamespace>b__2_0(INamespaceOrTypeSymbol s) in D:\api-docs-sync\src\PortToTripleSlash\src\libraries\AllTypesVisitor.cs:line 28
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ApiDocsSync.PortToTripleSlash.AllTypesVisitor.VisitNamespace(INamespaceSymbol symbol) in D:\api-docs-sync\src\PortToTripleSlash\src\libraries\AllTypesVisitor.cs:line 28
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamespaceSymbol.Accept(SymbolVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept(SymbolVisitor visitor)
   at ApiDocsSync.PortToTripleSlash.AllTypesVisitor.<VisitNamespace>b__2_0(INamespaceOrTypeSymbol s) in D:\api-docs-sync\src\PortToTripleSlash\src\libraries\AllTypesVisitor.cs:line 28
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by carlossanlop** [comment]
Reproing in debug shows that there is a `Debug.Assert` that we are hitting, but in release we aren't throwing.

Among all the symbols that get retrieved, interfaces get collected as well, in case there are any docs that need to be brought from an interface implementation.

Among those, there is `System.IAppDomainSetup`, for which we didn't find any symbols in the current assembly.

I think that if the API is an interface that does not belong to the current namespace or assembly, we should skip it. I'll try to create a fix for that.

**Comment by carlossanlop** [comment]
Or better yet - The list should not be null at that point.

**Comment by carlossanlop** [comment]
It seems the null was a separate problem, which I fixed, but the original error was still happening. Turns out that we cannot be using async methods along with a Parallel.ForEach inside the AllTypesVisitor. So I changed it to a good-ole sequential foreach and now the issue is gone.
